# Generated by Django 4.2.11 on 2024-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResetPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('is_confirmation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
