# Generated by Django 4.2.11 on 2024-04-07 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userresetpasswordcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresetpasswordcode',
            name='id',
        ),
        migrations.AddField(
            model_name='userresetpasswordcode',
            name='private_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
